// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("Plotly.NET.Interactive")>]
[<assembly: AssemblyProductAttribute("Plotly.NET")>]
[<assembly: AssemblyDescriptionAttribute("A F# interactive charting library using plotly.js")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "Plotly.NET.Interactive"

    [<Literal>]
    let AssemblyProduct = "Plotly.NET"

    [<Literal>]
    let AssemblyDescription =
        "A F# interactive charting library using plotly.js"

    [<Literal>]
    let AssemblyVersion = "2.0.0"

    [<Literal>]
    let AssemblyFileVersion = "2.0.0"
