module Tests.Charts3D

open Expecto
open Plotly.NET
open TestUtils
open Plotly.NET.GenericChart
open System

let scatterChart =
    let x = [19; 26; 55;]
    let y = [19; 26; 55;]
    let z = [19; 26; 55;]

    Chart.Scatter3d(x,y,z,StyleParam.Mode.Markers)
    |> Chart.withX_AxisStyle("my x-axis")
    |> Chart.withY_AxisStyle("my y-axis")
    |> Chart.withZ_AxisStyle("my z-axis")
    |> Chart.withSize(800.,800.)

[<Tests>]
let ``3D Scatter charts`` =
    testList "Charts3D.3D Scatter charts" [
        testCase "3D Scatter charts data" ( fun () ->
            "var data = [{\"type\":\"scatter3d\",\"x\":[19,26,55],\"y\":[19,26,55],\"z\":[19,26,55],\"mode\":\"markers\",\"line\":{},\"marker\":{}}];"
            |> chartGeneratedContains scatterChart
        );
        testCase "3D Scatter charts layout" ( fun () ->
            "var layout = {\"scene\":{\"xaxis\":{\"title\":\"my x-axis\"},\"yaxis\":{\"title\":\"my y-axis\"},\"zaxis\":{\"title\":\"my z-axis\"}},\"width\":800.0,\"height\":800.0};"
            |> chartGeneratedContains scatterChart
        );
    ]

let lineChart =
    let c = [0. .. 0.5 .. 15.]
    
    let x, y, z =  
        c
        |> List.map (fun i ->
            let i' = float i 
            let r = 10. * Math.Cos (i' / 10.)
            (r * Math.Cos i', r * Math.Sin i', i')
        )
        |> List.unzip3

    Chart.Scatter3d(x, y, z, StyleParam.Mode.Lines_Markers)
    |> Chart.withX_AxisStyle("x-axis")
    |> Chart.withY_AxisStyle("y-axis")
    |> Chart.withZ_AxisStyle("z-axis")
    |> Chart.withSize(800., 800.)


[<Tests>]
let ``Line charts`` =
    testList "Charts3D.Bar and column charts" [
        testCase " data" ( fun () ->
            "var data = [{\"type\":\"scatter3d\",\"x\":[10.0,8.764858122060915,5.3760304484812105,0.699428991431538,-4.078516059742164,-7.762380006776013,-9.457759559629629,-8.796818588044248,-6.020456431562834,-1.8981046678556164,2.4893698743024015,6.041583606256742,7.924627339505819,7.774455867055686,5.766162492106399,2.5362920361842747,-1.0137084976470045,-3.9731770939413367,-5.663676531805762,-5.800381805436716,-4.533522819483132,-2.3661340757417872,0.020074794419808174,1.9742392407015044,3.0577702559255746,3.1462811058452385,2.427409510770794,1.302916035546942,0.23240834306912295,-0.42769357063721014,-0.5373819709641076],\"y\":[0.0,4.788263815209447,8.372671348444594,9.862941931402888,8.911720173488927,5.798670944701264,1.3481709304529075,-3.2951619221615798,-6.970612585921842,-8.802141619140079,-8.415352216177444,-6.014904288506064,-2.306115620213046,1.7125353726077581,5.024910671806752,6.86324142009979,6.892925283704576,5.269880365378672,2.561769585348826,-0.43714135926897707,-2.9393586065447344,-4.37711141115013,-4.535916791549611,-3.576112184549465,-1.9443135767963393,-0.2091277735131711,1.123941901777903,1.7603416439605064,1.6837070198341995,1.1265744325858227,0.4599954209124893],\"z\":[0.0,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0],\"mode\":\"lines+markers\",\"line\":{},\"marker\":{}}];"
            |> chartGeneratedContains lineChart
        );
        testCase " layout" ( fun () ->
            "var layout = {\"scene\":{\"xaxis\":{\"title\":\"x-axis\"},\"yaxis\":{\"title\":\"y-axis\"},\"zaxis\":{\"title\":\"z-axis\"}},\"width\":800.0,\"height\":800.0};"
            |> chartGeneratedContains lineChart
        );
    ]

let firstSurfaceChart =
    //---------------------- Generate linearly spaced vector ----------------------
    let linspace (min,max,n) = 
        if n <= 2 then failwithf "n needs to be larger then 2"
        let bw = float (max - min) / (float n - 1.)
        Array.init n (fun i -> min + (bw * float i))
    
    //---------------------- Create example data ----------------------
    let size = 100
    let x = linspace(-2. * Math.PI, 2. * Math.PI, size)
    let y = linspace(-2. * Math.PI, 2. * Math.PI, size)
    
    let f x y = - (5. * x / (x**2. + y**2. + 1.) )
    
    let z = 
        Array.init size (fun i -> 
            Array.init size (fun j -> f x.[j] y.[i] )
                        )
    
    z
    |> Chart.Surface


let secondSurfaceChart =
    let x' = [0.;2.5]
    let y' = [0.;2.5]
    let z' = [
        [1.;1.;]; // row wise (length x)
        [1.;2.;];
        ] // column (length y)
    
    Chart.Surface(z', x', y', Opacity=0.5, Contours=Contours.initXyz(Show=true))

[<Tests>]
let ``Surface charts`` =
    testList "Charts3D.Surface charts" [
        testCase "First surface data" ( fun () ->
            // the data generated by this chart generates a
            // line of code which is 200 Kb long, unreasonably
            // huge for a test.
            [
                "var data = [{\"type\":\"surface\",\"z\":[[0.3929110807586562,0.39272903726671055,0.3923748718856843,0.3918384347714509,0.39110921172503726,0.39017633288191317,0.38902858492457726"
                "-0.3755066766683234,-0.38085145315419006,-0.38575670319102695,-0.3902383753762268,-0.3943127362115111,-0.3979962450330162,-0.4013054412792835"
                "-0.3901763328819132,-0.39110921172503726,-0.39183843477145097,-0.3923748718856844,-0.39272903726671055,-0.3929110807586562]]}];"
            ]
            |> chartGeneratedContainsList firstSurfaceChart
        );
        testCase "First surface layout" ( fun () ->
            emptyLayout firstSurfaceChart
        );
        testCase "Second surface data" ( fun () ->
            "var data = [{\"type\":\"surface\",\"z\":[[1.0,1.0],[1.0,2.0]],\"x\":[0.0,2.5],\"y\":[0.0,2.5],\"contours\":{\"x\":{\"show\":true},\"y\":{\"show\":true},\"z\":{\"show\":true}},\"opacity\":0.5}];"
            |> chartGeneratedContains secondSurfaceChart
        );
        testCase "Second surface layout" ( fun () ->
            emptyLayout secondSurfaceChart
        );
    ]