// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plotly.NET.WPF")>]
[<assembly: AssemblyProductAttribute("Plotly.NET")>]
[<assembly: AssemblyDescriptionAttribute("A F# interactive charting library using plotly.js")>]
[<assembly: AssemblyVersionAttribute("1.2.3")>]
[<assembly: AssemblyFileVersionAttribute("1.2.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plotly.NET.WPF"
    let [<Literal>] AssemblyProduct = "Plotly.NET"
    let [<Literal>] AssemblyDescription = "A F# interactive charting library using plotly.js"
    let [<Literal>] AssemblyVersion = "1.2.3"
    let [<Literal>] AssemblyFileVersion = "1.2.3"
