// this file was auto-generated using Plotly.NET.Codegen on 06.09.22 targeting Plotly.NET, Version=3.0.0.0, Culture=neutral, PublicKeyToken=c98c6d87097b7615.
// Do not edit this, as it will most likely be overwritten on the next codegen run.
// Instead, file an issue or target the codegen with your changes directly.
// Bugs that are not caused by wrong codegen are most likely not found in this file, but in the F# source this file is generated from.

namespace Plotly.NET.CSharp.LayoutObjects;

public static class Geo {
    public static Plotly.NET.LayoutObjects.Geo Init(
        Optional<Plotly.NET.StyleParam.GeoFitBounds> FitBounds = default,
        Optional<Plotly.NET.StyleParam.GeoResolution> Resolution = default,
        Optional<Plotly.NET.StyleParam.GeoScope> Scope = default,
        Optional<Plotly.NET.LayoutObjects.GeoProjection> Projection = default,
        Optional<System.Tuple<System.Double,System.Double>> Center = default,
        Optional<System.Boolean> Visible = default,
        Optional<Plotly.NET.LayoutObjects.Domain> Domain = default,
        Optional<System.Boolean> ShowCoastLines = default,
        Optional<Plotly.NET.Color> CoastLineColor = default,
        Optional<System.Double> CoastLineWidth = default,
        Optional<System.Boolean> ShowLand = default,
        Optional<Plotly.NET.Color> LandColor = default,
        Optional<System.Boolean> ShowOcean = default,
        Optional<Plotly.NET.Color> OceanColor = default,
        Optional<System.Boolean> ShowLakes = default,
        Optional<Plotly.NET.Color> LakeColor = default,
        Optional<System.Boolean> ShowRivers = default,
        Optional<Plotly.NET.Color> RiverColor = default,
        Optional<System.Double> RiverWidth = default,
        Optional<System.Boolean> ShowCountries = default,
        Optional<Plotly.NET.Color> CountryColor = default,
        Optional<System.Double> CountryWidth = default,
        Optional<System.Boolean> ShowSubunits = default,
        Optional<Plotly.NET.Color> SubunitColor = default,
        Optional<System.Double> SubunitWidth = default,
        Optional<System.Boolean> ShowFrame = default,
        Optional<Plotly.NET.Color> FrameColor = default,
        Optional<System.Double> FrameWidth = default,
        Optional<Plotly.NET.Color> BgColor = default,
        Optional<Plotly.NET.LayoutObjects.LinearAxis> LatAxis = default,
        Optional<Plotly.NET.LayoutObjects.LinearAxis> LonAxis = default
    )

        =>
            Plotly.NET.LayoutObjects.Geo.init(
                FitBounds: FitBounds.ToOption(),
                Resolution: Resolution.ToOption(),
                Scope: Scope.ToOption(),
                Projection: Projection.ToOption(),
                Center: Center.ToOption(),
                Visible: Visible.ToOption(),
                Domain: Domain.ToOption(),
                ShowCoastLines: ShowCoastLines.ToOption(),
                CoastLineColor: CoastLineColor.ToOption(),
                CoastLineWidth: CoastLineWidth.ToOption(),
                ShowLand: ShowLand.ToOption(),
                LandColor: LandColor.ToOption(),
                ShowOcean: ShowOcean.ToOption(),
                OceanColor: OceanColor.ToOption(),
                ShowLakes: ShowLakes.ToOption(),
                LakeColor: LakeColor.ToOption(),
                ShowRivers: ShowRivers.ToOption(),
                RiverColor: RiverColor.ToOption(),
                RiverWidth: RiverWidth.ToOption(),
                ShowCountries: ShowCountries.ToOption(),
                CountryColor: CountryColor.ToOption(),
                CountryWidth: CountryWidth.ToOption(),
                ShowSubunits: ShowSubunits.ToOption(),
                SubunitColor: SubunitColor.ToOption(),
                SubunitWidth: SubunitWidth.ToOption(),
                ShowFrame: ShowFrame.ToOption(),
                FrameColor: FrameColor.ToOption(),
                FrameWidth: FrameWidth.ToOption(),
                BgColor: BgColor.ToOption(),
                LatAxis: LatAxis.ToOption(),
                LonAxis: LonAxis.ToOption()
            );
    public static Plotly.NET.LayoutObjects.Geo Style(
        this Plotly.NET.LayoutObjects.Geo obj,
        Optional<Plotly.NET.StyleParam.GeoFitBounds> FitBounds = default,
        Optional<Plotly.NET.StyleParam.GeoResolution> Resolution = default,
        Optional<Plotly.NET.StyleParam.GeoScope> Scope = default,
        Optional<Plotly.NET.LayoutObjects.GeoProjection> Projection = default,
        Optional<System.Tuple<System.Double,System.Double>> Center = default,
        Optional<System.Boolean> Visible = default,
        Optional<Plotly.NET.LayoutObjects.Domain> Domain = default,
        Optional<System.Boolean> ShowCoastLines = default,
        Optional<Plotly.NET.Color> CoastLineColor = default,
        Optional<System.Double> CoastLineWidth = default,
        Optional<System.Boolean> ShowLand = default,
        Optional<Plotly.NET.Color> LandColor = default,
        Optional<System.Boolean> ShowOcean = default,
        Optional<Plotly.NET.Color> OceanColor = default,
        Optional<System.Boolean> ShowLakes = default,
        Optional<Plotly.NET.Color> LakeColor = default,
        Optional<System.Boolean> ShowRivers = default,
        Optional<Plotly.NET.Color> RiverColor = default,
        Optional<System.Double> RiverWidth = default,
        Optional<System.Boolean> ShowCountries = default,
        Optional<Plotly.NET.Color> CountryColor = default,
        Optional<System.Double> CountryWidth = default,
        Optional<System.Boolean> ShowSubunits = default,
        Optional<Plotly.NET.Color> SubunitColor = default,
        Optional<System.Double> SubunitWidth = default,
        Optional<System.Boolean> ShowFrame = default,
        Optional<Plotly.NET.Color> FrameColor = default,
        Optional<System.Double> FrameWidth = default,
        Optional<Plotly.NET.Color> BgColor = default,
        Optional<Plotly.NET.LayoutObjects.LinearAxis> LatAxis = default,
        Optional<Plotly.NET.LayoutObjects.LinearAxis> LonAxis = default
    )

        =>
            Plotly.NET.LayoutObjects.Geo.style(
                FitBounds: FitBounds.ToOption(),
                Resolution: Resolution.ToOption(),
                Scope: Scope.ToOption(),
                Projection: Projection.ToOption(),
                Center: Center.ToOption(),
                Visible: Visible.ToOption(),
                Domain: Domain.ToOption(),
                ShowCoastLines: ShowCoastLines.ToOption(),
                CoastLineColor: CoastLineColor.ToOption(),
                CoastLineWidth: CoastLineWidth.ToOption(),
                ShowLand: ShowLand.ToOption(),
                LandColor: LandColor.ToOption(),
                ShowOcean: ShowOcean.ToOption(),
                OceanColor: OceanColor.ToOption(),
                ShowLakes: ShowLakes.ToOption(),
                LakeColor: LakeColor.ToOption(),
                ShowRivers: ShowRivers.ToOption(),
                RiverColor: RiverColor.ToOption(),
                RiverWidth: RiverWidth.ToOption(),
                ShowCountries: ShowCountries.ToOption(),
                CountryColor: CountryColor.ToOption(),
                CountryWidth: CountryWidth.ToOption(),
                ShowSubunits: ShowSubunits.ToOption(),
                SubunitColor: SubunitColor.ToOption(),
                SubunitWidth: SubunitWidth.ToOption(),
                ShowFrame: ShowFrame.ToOption(),
                FrameColor: FrameColor.ToOption(),
                FrameWidth: FrameWidth.ToOption(),
                BgColor: BgColor.ToOption(),
                LatAxis: LatAxis.ToOption(),
                LonAxis: LonAxis.ToOption()
            ).Invoke(obj);
}