// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Plotly")>]
[<assembly: AssemblyProductAttribute("FSharp.Plotly")>]
[<assembly: AssemblyDescriptionAttribute("A F# interactive charting library using plotly.js")>]
[<assembly: AssemblyVersionAttribute("1.2.0")>]
[<assembly: AssemblyFileVersionAttribute("1.2.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Plotly"
    let [<Literal>] AssemblyProduct = "FSharp.Plotly"
    let [<Literal>] AssemblyDescription = "A F# interactive charting library using plotly.js"
    let [<Literal>] AssemblyVersion = "1.2.0"
    let [<Literal>] AssemblyFileVersion = "1.2.0"
    let [<Literal>] AssemblyConfiguration = "Release"
