// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plotly.NET.Interactive.Extension")>]
[<assembly: AssemblyProductAttribute("Plotly.NET")>]
[<assembly: AssemblyDescriptionAttribute("A F# interactive charting library using plotly.js")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plotly.NET.Interactive.Extension"
    let [<Literal>] AssemblyProduct = "Plotly.NET"
    let [<Literal>] AssemblyDescription = "A F# interactive charting library using plotly.js"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
